spring.application.name=Spring-ChatBot-demo

spring.datasource.url=jdbc:postgresql://localhost:5432/chatbotdb
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.ai.vectorstore.pgvector.initialize-schema=true por el momento hasta tener instalacion de pgvector
spring.ai.vectorstore.pgvector.initialize-schema=false
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=llama3